services:
  # Backend (FastAPI)
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend  # Ensure this points to the backend Dockerfile
    container_name: scriptura-backend
    volumes:
      - ./data:/app/data
    ports:
      - "8000:8000"
    environment:
      - ENV=production
    restart: unless-stopped

  # Frontend (React)
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend  # Make sure to point to the React Dockerfile
    container_name: scriptura-frontend
    ports:
      - "80:80"  # Exposing port 80 for nginx
    depends_on:
      - backend  # Ensure backend is available before frontend starts
    restart: unless-stopped
